stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

test_job:
  stage: test
  image: node:14
  script:
    - npm test

deploy_job:
  stage: deploy
  image: node:14
  script:
    - echo "Deploy step here"

